### PR TITLE
Update experiment to version 0.3.0 of mitosis

### PR DESCRIPTION
**Pull request by Jacob-Stevens-Haas**
This change removes the CLI from gen-experiments and uses the new generic CLI from mitosis.  See examples in the `experiment-scripts` branch:
```
nohup mitosis gen_experiments.gridsearch \
    --eval-param seed=19 \
    --group lorenz \
    --folder trials \
    --param metrics=all \
    --param other_params=lor-ross-cubic \
    --param grid_params=duration-absnoise \
    --param grid_vals=duration-absnoise \
    --param grid_decisions=plot2 \
    --param series_params=kalman-auto3 \
    --param +plot_prefs=test-absrel5 \
    --param +skinny_specs=duration-noise &> lorenz.log &
```
Once installed, mitosis has a decent tooltip from `mitosis --help`/`mitosis -h`.

# Why

The old version of mitosis loaded the parameters (which could use any arbitrary python objects) and sent them to the jupyter notebook via pickle.  For complex objects like gurobipy optimizers (in MIOSR), this would cause errors.  It also required some fancy loading logic in this repo.  Now, parameters are split into two types: eval (like seed=19) and lookup (like metrics=all).  The latter are simply defined in a regular python dictionary (or in this case, a nested dictionary).

### CODE REVIEW

**Comment by Jacob-Stevens-Haas** [comment]
Also @yb6599 , because another group is using mitosis too, I'm going to be pretty regular about releasing new mitosis versions on pypi.

**Comment by yb6599** [comment]
So I can run experiments once this PR is merged? Or is there another alternative?

**Comment by yb6599** [comment]
For `--param +plot_prefs=test-absrel5 \
 --param +skinny_specs=duration-noise` 
What does the '+' before plot_prefs and skinny_specs represent?

**Comment by Jacob-Stevens-Haas** [comment]
Good questions.  Mitosis 0.3.0 added [the `+`](https://github.com/Jacob-Stevens-Haas/mitosis#untracked-parameters).
 
> nested dictionaries such as sims_params, diff_params, feat_params, etc

These are now in config.py.  See: [`vars(config)`](https://github.com/Jacob-Stevens-Haas/gen-experiments/blob/a31a067694c7b9c07f715a72e965bb71a4e0de73/src/gen_experiments/gridsearch.py#L37C1-L37C27)

**Review by yb6599 — APPROVED** [review]
Looks good! Looks like similar chages must be done in pdes.py for it to work properly.

**Comment by yb6599** [comment]
>Now, parameters are split into two types: eval (like seed=19) and lookup (like metrics=all).
Are there more eval parameters other than seed?

**Comment by Jacob-Stevens-Haas** [comment]
> Looks good! Looks like similar changes must be done in pdes.py for it to work properly.

Yep, definitely

**Pull request merged**
